export const BOOK_CREATE_REQUEST = 'BOOK_CREATE_REQUEST';
export const BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS';
export const BOOK_CREATE_FAIL = 'BOOK_CREATE_FAIL';
export const BOOK_CREATE_RESET = 'BOOK_CREATE_RESET';

export const BOOK_DETAILS_REQUEST = 'BOOK_DETAILS_REQUEST';
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS';
export const BOOK_DETAILS_FAIL = 'BOOK_DETAILS_FAIL';